# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelezionaProgettoDaEliminare.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelezionaProgetto(object):
    def setupUi(self, SelezionaProgetto):
        SelezionaProgetto.setObjectName("SelezionaProgetto")
        SelezionaProgetto.resize(516, 301)
        self.gridLayout = QtWidgets.QGridLayout(SelezionaProgetto)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(SelezionaProgetto)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.listView = QtWidgets.QListView(SelezionaProgetto)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelezionaProgetto)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SelezionaProgetto)
        self.buttonBox.rejected.connect(SelezionaProgetto.reject) # type: ignore
        self.buttonBox.accepted.connect(SelezionaProgetto.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelezionaProgetto)

    def retranslateUi(self, SelezionaProgetto):
        _translate = QtCore.QCoreApplication.translate
        SelezionaProgetto.setWindowTitle(_translate("SelezionaProgetto", "Seleziona file IFC"))
